### ISSUE TITLE
Design: Generic over Conversion Mode

### ISSUE THREAD

**Issue by dbrgn** [dbrgn/mcp3425-rs#1]
The MCP3425 ADC has two conversion modes: One-shot conversion, where a single conversion is triggered followed by standby, or continuous conversion, where measurements are being done continuously.

I wanted to implement the driver in a way that it's fully type safe, so that one cannot trigger a one-shot measurement when it's configured in continuous conversion mode. (Technically that would work, it would simply re-configure the ADC to one-shot mode during measurement, but I think conceptually it's confusing if the device changes the mode during a measurement.).

So what I did was to make the driver [generic](https://docs.rs/mcp3425/0.1.0/mcp3425/struct.MCP3425.html) over the [ConversionMode](https://docs.rs/mcp3425/0.1.0/mcp3425/trait.ConversionMode.html). This allows you to instantiate either a `MCP3425<OneShotMode>` or a `MCP3425<ContinuousMode>`.

The problem is that I didn't find a way to write a method that would convert one variant of the driver into the other one. Maybe someone here has more experience with generic and can point me to a way of writing such a method?

Also, I wonder if this is slightly overengineered and if I should simply return an error if someone tries to trigger a oneshot conversion in continuous conversion mode or vice versa.

**Comment by therealprof** [comment]
Using state types is a much better idea than throwing errors since incorrect use will be flagged by the compiler.

To do this you have two options:
* The `Into` trait which allows you to automatically turn types into other types by implementing the trait.
* Explicit conversion functions

I think the latter is less surprising and rather simple to implement, here's a small mockup:
```
impl MCP3425<OneShotMode> {
    pub fn into_continuous(self) -> MCP3425<ContinuousMode> {
        // Magic stuff, like changing registers
        MCP3425<ContinuousMode> { self }
    }
}

impl MCP3425<ContinuousMode> {
    pub fn into_oneshot(self) -> MCP3425<OneShotMode> {
        // Magic stuff, like changing registers
        MCP3425<OneShotMode> { self }
    }
}
```

**Comment by dbrgn** [comment]
Huh, that works... I think I tried that before, but must have messed up something. Thanks! :)

When implementing this, we must be very careful to handle the `config` field correctly. It probably needs to be cleared, because in oneshot mode doing a measurement changes the configuration.

**Comment by dbrgn** [comment]
Actually by calling the appropriate constructor function from the conversion functions that issue will already be covered :slightly_smiling_face:
