### ISSUE TITLE
Design: Measurement Freshness

### ISSUE THREAD

**Issue by dbrgn** [dbrgn/mcp3425-rs#3]
In continuous conversion mode, the ADC conversions are triggered periodically by a timer inside the device. If a user reads a measurement value twice in a row, the second value will be "stale" because no new measurement by the ADC has taken place since the previous value returned.

I could think of three ways to handle this:

- If the value is not "fresh", I return an error
- I return a tuple with the value returned and with the flag that indicates whether the data was fresh or not
- The more rusty way: A [`Measurement`](https://docs.rs/mcp3425/0.1.0/mcp3425/enum.Measurement.html) enum that can be either `Fresh(i16)` or `NotFresh(i16)`.

I implemented the third approach. It requires to *always* match on the measurement result though. Is this a good idea? Maybe an `.unwrap()` method that ignores the freshness should be provided?

**Comment by therealprof** [comment]
I think you should ask yourself this: Is a `NotFresh` measurement of any relevance to the application? If not, then just report "fresh" values and an error otherwise. If a `NotFresh` value might be relevant for debugging you could still pass it along in an `Error` type.

**Comment by dbrgn** [comment]
It's not necessarily a "wrong" value, it might just be that the user polled the device too quickly.

On the other hand returning an `Error::NotReady` might be a good option to handle this too.

**Comment by therealprof** [comment]
My point here is: If it's a "good" (whatever the definition of good may be) value, return it, if something's off tell the user and let him deal with it.

**Comment by dbrgn** [comment]
It depends a bit. In the first version the `set_config` function did not block until the first measurement was ready, so it would have been possible that an old (potentially hours or days) or completely wrong measurement would be returned when setting the configuration and immediately reading the measurement (before the first conversion has finished). In that case I'd consider the measurement "bad".

In the meantime I changed the `set_config` function so that it blocks until the configuration has been set and the first value is ready. Now that case should not be possible anymore. The only remaining source for a `NotFresh` value is if you poll the ADC too quickly, so that the same measurement is read twice. In that case it could be considered a "good" value, but the user should know that it hasn't been updated. It could also be considered a "bad" value, because the user intended to trigger a measurement, but a new measurement was not yet ready so the previous value was returned.
