### ISSUE TITLE
Design: Saturation / Out of range

### ISSUE THREAD

**Issue by dbrgn** [dbrgn/mcp3425-rs#4]
If a voltage is too high or too low to be measured, the value read from the ADC will be a certain saturation pattern.

Currently I treat these two patterns like errors and return either `Error::VoltageTooHigh` or `Error::VoltageTooLow`. Is it a good idea to treat saturation as errors, or are they just special cases of a result value that should be returned maybe as an enum?

This also causes a bit of an issue in combination with the [freshness checks](https://github.com/dbrgn/mcp3425-rs/issues/3). If the user first does a measurement with a voltage that is too hight to be measured, that will return an error. The saturated value will be persisted in the ADC though. If the voltage immediately drops to a measurable range and the user measures the voltage again immediately, without the next ADC conversion being ready, then the user would probably expect a `NotFresh(...)` response. Instead, an error is returned becaue the previously stored value in the data register still matches the saturation pattern. The error completely masks the freshness information.

**Comment by therealprof** [comment]
> Currently I treat these two patterns like errors and return either Error::VoltageTooHigh or Error::VoltageTooLow. Is it a good idea to treat saturation as errors, or are they just special cases of a result value that should be returned maybe as an enum?

It'd say `Error` is the to go, as that's the point of returning `Result`.

> This also causes a bit of an issue in combination with the freshness checks.

I would expect this to be handled by an application using the driver, you just to provide the tools necessary to deal with that. E.g. if the driver returns with an `Error` the application will be able to match on that, clear the error (that's something you should provide in the driver) and retry the measurement until successful (or maybe give up at some point).

**Comment by dbrgn** [comment]
Hm, if we'd convert the `NotFresh` variant to an error (see #3), then this issue would be resolved too :)
