### ISSUE TITLE
Design: Newtype for Return Value?

### ISSUE THREAD

**Issue by dbrgn** [dbrgn/mcp3425-rs#6]
The return value of a measurement is an i16 with millivolts.

Should this be a newtype with conversion methods instead?

**Comment by therealprof** [comment]
I was thinking of relying on https://github.com/jocull/rust-measurements for that. Unfortunately it doesn't support voltages just yet.

**Comment by dbrgn** [comment]
Nice, a general crate for units might be a good idea. That crate is not `no_std` though, it seems (unless I looked in the wrong place).

**Comment by dbrgn** [comment]
Here would be another crate that does something similar, and that is `no_std`: https://github.com/iliekturtles/uom

I think for now I'll just write my own wrapper, with the option of replacing it with one of those libraries if one of them becomes something of a standard. (That could also be done as an optional feature.)

**Comment by therealprof** [comment]
Hm, weird. @thejpster recommended it a few days ago and he's also an embedded guy so I assumed it was `no_std`. OTOH it should be too hard to make it `no_std`.

**Comment by thejpster** [comment]
It's partly my crate (now) but I've only used it on a Raspberry Pi. Please do send a PR to make it no_std and add Voltage/Current/Resistance.

**Comment by thejpster** [comment]
https://docs.rs/measurements/0.7.0/measurements/ now builds as `#![no_std]`.

I used the `time` crate as a substitute for `std::time` as core doesn't seem to have anything equivalent.

**Comment by dbrgn** [comment]
@thejpster that was fast, thanks! :slightly_smiling_face: I think I'll add your crate as an optional feature for now. If many crates start to adopt it, we can still make it the standard.

**Comment by dbrgn** [comment]
@thejpster how do you handle small units? I think you're using `f64` values for the base units, right?

The advantage of a custom solution is that I can store the voltages in millivolts as `i16`, since I now that the precision won't get higher than that. On 64 bit Linux systems that might not really matter, but on small 32 bit microcontrollers without FPU it might be highly preferrable to work with integers.

**Comment by thejpster** [comment]
Yeah, it's a design trade. `uom` lets you pick your base units, the crate I adopted for `sensehat` just uses f64, which I think makes it much simpler. If you can't do what you're doing in an f64, or where you have a lot of units and can't afford the 8 bytes, then please do use the other crate. For me (and for the Sense Hat) I couldn't think of a scenario where that would matter though.
